"""Initial migration

Revision ID: 435cbb71e08f
Revises: 
Create Date: 2022-12-01 22:45:11.942226

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '435cbb71e08f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dice2')
    op.drop_table('dice1')
    with op.batch_alter_table('dice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.alter_column('Job_Title',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=500),
               nullable=False)
        batch_op.alter_column('Company_Name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=500),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=1000),
               nullable=False)
        batch_op.alter_column('Posted_Date',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.DateTime(),
               nullable=False)
        batch_op.alter_column('Job_Type',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.String(length=300),
               nullable=False)
        batch_op.alter_column('Location',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=300),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dice', schema=None) as batch_op:
        batch_op.alter_column('Location',
               existing_type=sa.String(length=300),
               type_=mysql.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('Job_Type',
               existing_type=sa.String(length=300),
               type_=mysql.VARCHAR(length=30),
               nullable=True)
        batch_op.alter_column('Posted_Date',
               existing_type=sa.DateTime(),
               type_=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=1000),
               nullable=True)
        batch_op.alter_column('Company_Name',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('Job_Title',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('id')

    op.create_table('dice1',
    sa.Column('Job_Title', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('Company_Name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('Posted_Date', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Job_Type', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('Location', mysql.VARCHAR(length=100), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('dice2',
    sa.Column('Job_Title', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('Company_Name', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('Posted_Date', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Job_Type', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('Location', mysql.VARCHAR(length=300), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
